"""Generate the temporary development key for the radio link.

Both boards must be flashed with the same key, so run this once and
build both boards from the same checkout. The key file is git-ignored
(the .gitignore "secrets/" rule) and must never be committed: anyone
who knows the key can read and forge radio traffic.

This key is a stand-in until pairing (Phase 5) lets the two devices
derive a key themselves.

Usage:
    python tools/make_dev_key.py            # create the key
    python tools/make_dev_key.py --force    # replace it (reflash both boards)
"""

import argparse
import secrets
import sys
from pathlib import Path

KEY_FILE = (Path(__file__).resolve().parent.parent
            / "firmware" / "include" / "secrets" / "dev_key.h")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--force", action="store_true",
                        help="replace an existing key (reflash both boards afterwards)")
    args = parser.parse_args()

    if KEY_FILE.exists() and not args.force:
        sys.exit(f"{KEY_FILE} already exists. Use --force to replace it.")

    key = secrets.token_bytes(16)   # from the OS's cryptographic RNG
    body = ", ".join(f"0x{b:02X}" for b in key)
    KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
    KEY_FILE.write_text(
        "// Generated by tools/make_dev_key.py. DO NOT COMMIT (git-ignored).\n"
        "// Temporary development key for the radio link; pairing replaces it in Phase 5.\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        f"static const uint8_t DEV_RADIO_KEY[16] = {{{body}}};\n"
    )
    print(f"Wrote {KEY_FILE}")


if __name__ == "__main__":
    main()
